---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.name }}
  ports:
    - port: {{ .Values.options.port }}
      targetPort: {{ .Values.options.port }}